function Type(name, label, abbreviation) {
    this.name = name;
    this.label = label;
    this.abbreviation = abbreviation;
}

function Fuel(name, label, abbreviation) {
    Type.call(this, name, label, abbreviation);
}

function Oil(name, label, abbreviation) {
    Type.call(this, name, label, abbreviation);
}

function BatteryGroupSize(name, label, abbreviation) {
    Type.call(this, name, label, abbreviation);
}

var Regular = new Fuel("Regular", "regular gasoline", "regular");
Object.freeze(Regular);
var Plus = new Fuel("Plus", "plus gasoline", "plus");
Object.freeze(Plus);
var PremiumFuel = new Fuel("Premium", "premium gasoline", "premium");
Object.freeze(PremiumFuel);
var Diesel = new Fuel("Diesel", "diesel", "diesel");
Object.freeze(Diesel);
var E85 = new Fuel("E85", "ethanol 85", "E85");
Object.freeze(E85);
var Electric = new Fuel("Electric", "electric", "electric");
Object.freeze(Electric);
var CNG = new Fuel("CNG", "compressed natural gas", "CNG");
Object.freeze(CNG);
var LPG = new Fuel("LPG", "liquefied petroleum gasoline", "LPG");
Object.freeze(LPG);

var Standard = new Oil("Standard", "Standard", "std");
Object.freeze(Standard);
var PremiumOil = new Oil("Premium", "Premium", "prem");
Object.freeze(PremiumOil);
var HighPremium = new Oil("HighPremium", "High premium", "high prem");
Object.freeze(HighPremium);

var BCI_21 = new BatteryGroupSize("BCI_21", "21", "21");
Object.freeze(BCI_21);
var BCI_22F = new BatteryGroupSize("BCI_22F", "22F", "22F");
Object.freeze(BCI_22F);
var BCI_22HF = new BatteryGroupSize("BCI_22HF", "22HF", "22HF");
Object.freeze(BCI_22HF);
var BCI_22NF = new BatteryGroupSize("BCI_22NF", "22NF", "22NF");
Object.freeze(BCI_22NF);
var BCI_22R = new BatteryGroupSize("BCI_22R", "22R", "22R");
Object.freeze(BCI_22R);
var BCI_24 = new BatteryGroupSize("BCI_24", "24", "24");
Object.freeze(BCI_24);
var BCI_24F = new BatteryGroupSize("BCI_24F", "24F", "24F");
Object.freeze(BCI_24F);
var BCI_24H = new BatteryGroupSize("BCI_24H", "24H", "24H");
Object.freeze(BCI_24H);
var BCI_24R = new BatteryGroupSize("BCI_24R", "24R", "24R");
Object.freeze(BCI_24R);
var BCI_24T = new BatteryGroupSize("BCI_24T", "24T", "24T");
Object.freeze(BCI_24T);
var BCI_25 = new BatteryGroupSize("BCI_25", "25", "25");
Object.freeze(BCI_25);
var BCI_26 = new BatteryGroupSize("BCI_26", "26", "26");
Object.freeze(BCI_26);
var BCI_26R = new BatteryGroupSize("BCI_26R", "26R", "26R");
Object.freeze(BCI_26R);
var BCI_27 = new BatteryGroupSize("BCI_27", "27", "27");
Object.freeze(BCI_27);
var BCI_27F = new BatteryGroupSize("BCI_27F", "27F", "27F");
Object.freeze(BCI_27F);
var BCI_27H = new BatteryGroupSize("BCI_27H", "27H", "27H");
Object.freeze(BCI_27H);
var BCI_29NF = new BatteryGroupSize("BCI_29NF", "29NF", "29NF");
Object.freeze(BCI_29NF);
var BCI_33 = new BatteryGroupSize("BCI_33", "33", "33");
Object.freeze(BCI_33);
var BCI_34 = new BatteryGroupSize("BCI_34", "34", "34");
Object.freeze(BCI_34);
var BCI_34R = new BatteryGroupSize("BCI_34R", "34R", "34R");
Object.freeze(BCI_34R);
var BCI_35 = new BatteryGroupSize("BCI_35", "35", "35");
Object.freeze(BCI_35);
var BCI_36R = new BatteryGroupSize("BCI_36R", "36R", "36R");
Object.freeze(BCI_36R);
var BCI_40R = new BatteryGroupSize("BCI_40R", "40R", "40R");
Object.freeze(BCI_40R);
var BCI_41 = new BatteryGroupSize("BCI_41", "41", "41");
Object.freeze(BCI_41);
var BCI_42 = new BatteryGroupSize("BCI_42", "42", "42");
Object.freeze(BCI_42);
var BCI_43 = new BatteryGroupSize("BCI_43", "43", "43");
Object.freeze(BCI_43);
var BCI_45 = new BatteryGroupSize("BCI_45", "45", "45");
Object.freeze(BCI_45);
var BCI_46 = new BatteryGroupSize("BCI_46", "46", "46");
Object.freeze(BCI_46);
var BCI_47 = new BatteryGroupSize("BCI_47", "47", "47");
Object.freeze(BCI_47);
var BCI_48 = new BatteryGroupSize("BCI_48", "48", "48");
Object.freeze(BCI_48);
var BCI_49 = new BatteryGroupSize("BCI_49", "49", "49");
Object.freeze(BCI_49);
var BCI_50 = new BatteryGroupSize("BCI_50", "50", "50");
Object.freeze(BCI_50);
var BCI_51 = new BatteryGroupSize("BCI_51", "51", "51");
Object.freeze(BCI_51);
var BCI_51R = new BatteryGroupSize("BCI_51R", "51R", "51R");
Object.freeze(BCI_51R);
var BCI_52 = new BatteryGroupSize("BCI_52", "52", "52");
Object.freeze(BCI_52);
var BCI_53 = new BatteryGroupSize("BCI_53", "53", "53");
Object.freeze(BCI_53);
var BCI_54 = new BatteryGroupSize("BCI_54", "54", "54");
Object.freeze(BCI_54);
var BCI_55 = new BatteryGroupSize("BCI_55", "55", "55");
Object.freeze(BCI_55);
var BCI_56 = new BatteryGroupSize("BCI_56", "56", "56");
Object.freeze(BCI_56);
var BCI_57 = new BatteryGroupSize("BCI_57", "57", "57");
Object.freeze(BCI_57);
var BCI_58 = new BatteryGroupSize("BCI_58", "58", "58");
Object.freeze(BCI_58);
var BCI_58R = new BatteryGroupSize("BCI_58R", "58R", "58R");
Object.freeze(BCI_58R);
var BCI_59 = new BatteryGroupSize("BCI_59", "59", "59");
Object.freeze(BCI_59);
var BCI_60 = new BatteryGroupSize("BCI_60", "60", "60");
Object.freeze(BCI_60);
var BCI_61 = new BatteryGroupSize("BCI_61", "61", "61");
Object.freeze(BCI_61);
var BCI_62 = new BatteryGroupSize("BCI_62", "62", "62");
Object.freeze(BCI_62);
var BCI_63 = new BatteryGroupSize("BCI_63", "63", "63");
Object.freeze(BCI_63);
var BCI_64 = new BatteryGroupSize("BCI_64", "64", "64");
Object.freeze(BCI_64);
var BCI_65 = new BatteryGroupSize("BCI_65", "65", "65");
Object.freeze(BCI_65);
var BCI_70 = new BatteryGroupSize("BCI_70", "70", "70");
Object.freeze(BCI_70);
var BCI_71 = new BatteryGroupSize("BCI_71", "71", "71");
Object.freeze(BCI_71);
var BCI_72 = new BatteryGroupSize("BCI_72", "72", "72");
Object.freeze(BCI_72);
var BCI_73 = new BatteryGroupSize("BCI_73", "73", "73");
Object.freeze(BCI_73);
var BCI_74 = new BatteryGroupSize("BCI_74", "74", "74");
Object.freeze(BCI_74);
var BCI_75 = new BatteryGroupSize("BCI_75", "75", "75");
Object.freeze(BCI_75);
var BCI_76 = new BatteryGroupSize("BCI_76", "76", "76");
Object.freeze(BCI_76);
var BCI_78 = new BatteryGroupSize("BCI_78", "78", "78");
Object.freeze(BCI_78);
var BCI_85 = new BatteryGroupSize("BCI_85", "85", "85");
Object.freeze(BCI_85);
var BCI_86 = new BatteryGroupSize("BCI_86", "86", "86");
Object.freeze(BCI_86);
var BCI_90 = new BatteryGroupSize("BCI_90", "90", "90");
Object.freeze(BCI_90);
var BCI_91 = new BatteryGroupSize("BCI_91", "91", "91");
Object.freeze(BCI_91);
var BCI_92 = new BatteryGroupSize("BCI_92", "92", "92");
Object.freeze(BCI_92);
var BCI_93 = new BatteryGroupSize("BCI_93", "93", "93");
Object.freeze(BCI_93);
var BCI_95R = new BatteryGroupSize("BCI_95R", "95R", "95R");
Object.freeze(BCI_95R);
var BCI_96R = new BatteryGroupSize("BCI_96R", "96R", "96R");
Object.freeze(BCI_96R);
var BCI_97R = new BatteryGroupSize("BCI_97R", "97R", "97R");
Object.freeze(BCI_97R);
var BCI_98R = new BatteryGroupSize("BCI_98R", "98R", "98R");
Object.freeze(BCI_98R);